### ISSUE TITLE
Add descritption on how to download the complete output folder via command line

### ISSUE THREAD

**Issue by eHanseJoerg** [floydhub/floyd-docs#9]
The documentation describes the command `floyd [-u] output` . Unfortunately, it will only provide a link to be opened in a browser. Not good if you are logging in from a console only machine!

Add description on how to get the files via command line (for example in combination with wget)

**Comment by narenst** [comment]
This is fixed now. The new doc is available at: http://docs.floydhub.com/commands/output/#downloading-output

We are also changing this page on the dashboard to make downloading output an easier option.

**Comment by eHanseJoerg** [comment]
@narenst, 
 
your fix still does not explain how to download all output via command line only, without using a browser.
